# Generated by Django 4.0.5 on 2023-02-18 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guessNumber', models.IntegerField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='core.gameround')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.AddField(
            model_name='gameround',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.CreateModel(
            name='GameRoundLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.gameround')),
            ],
            options={
                'unique_together': {('game_round', 'lat', 'long')},
            },
        ),
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_game_round'),
        ),
    ]
