# Generated by Django 4.0.5 on 2023-02-18 17:29
import csv
from django.db import migrations
from geodle.core.models import Location

def populate_locations(apps, schema_editor):

    with open('geodle/core/countries.csv', 'r') as countries_csv:
        reader = csv.reader(countries_csv)
        next(reader)
        for line in reader:
            location = Location(name=line[0], lat=line[1], long=line[2], id=line[3])
            location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_locations),
    ]
