# Generated by Django 4.0.5 on 2023-02-16 11:18
import csv
from django.db import migrations
from geodle.core.models import Location

def populate_locations(apps, schema_editor):
    with open('geodle/core/countries.csv','r') as location_csv:
        reader = csv.reader(location_csv)
        next(reader)
        for row in reader:
            location = Location(name=row[0], lat=row[1], long=row[2], id=row[3])
            location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_guess_ip'),
    ]

    operations = [
        migrations.RunPython(populate_locations)
    ]
